<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        // Get the first available category
        $categoryId = DB::table('categories')->value('id');

        if (!$categoryId) {
            $this->command->error(
                'No category found. Please create at least one category first.'
            );

            return;
        }

        $recipes = [

            // 1. Chicken Biryani
            [
                'title' => 'Chicken Biryani',
                'slug' => 'chicken-biryani',
                'description' => 'A flavorful Pakistani rice dish made with spiced chicken and aromatic basmati rice.',
                'cuisine_type' => 'Pakistani',
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'cooking_time' => 60,
                'servings' => 4,
                'calories' => 520,
                'protein' => 28.00,
                'carbs' => 65.00,
                'fats' => 16.00,
                'fiber' => 3.00,
                'sugar' => 4.00,
                'sodium' => 720.00,
                'spice_level' => 'spicy',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1563379091339-03246963d96c',
                'health_score' => 75,
                'avg_rating' => 4.70,
                'review_count' => 125,
                'view_count' => 1500,
                'is_featured' => true,
                'allergens' => json_encode(['dairy']),
                'estimated_cost' => 12.50,
            ],

            // 2. Creamy Chicken Pasta
            [
                'title' => 'Creamy Chicken Pasta',
                'slug' => 'creamy-chicken-pasta',
                'description' => 'A creamy and delicious chicken pasta recipe perfect for a quick dinner.',
                'cuisine_type' => 'Italian',
                'meal_type' => 'dinner',
                'difficulty' => 'easy',
                'cooking_time' => 30,
                'servings' => 3,
                'calories' => 580,
                'protein' => 32.00,
                'carbs' => 70.00,
                'fats' => 20.00,
                'fiber' => 4.00,
                'sugar' => 5.00,
                'sodium' => 650.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'health_score' => 70,
                'avg_rating' => 4.50,
                'review_count' => 98,
                'view_count' => 1200,
                'is_featured' => true,
                'allergens' => json_encode(['dairy', 'gluten']),
                'estimated_cost' => 10.00,
            ],

            // 3. Vegetable Salad
            [
                'title' => 'Vegetable Salad',
                'slug' => 'vegetable-salad',
                'description' => 'A fresh and healthy vegetable salad packed with nutrients.',
                'cuisine_type' => 'Mediterranean',
                'meal_type' => 'lunch',
                'difficulty' => 'beginner',
                'cooking_time' => 10,
                'servings' => 2,
                'calories' => 220,
                'protein' => 6.00,
                'carbs' => 20.00,
                'fats' => 12.00,
                'fiber' => 6.00,
                'sugar' => 7.00,
                'sodium' => 250.00,
                'spice_level' => 'mild',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
                'health_score' => 90,
                'avg_rating' => 4.80,
                'review_count' => 210,
                'view_count' => 2300,
                'is_featured' => true,
                'allergens' => null,
                'estimated_cost' => 6.50,
            ],

            // 4. Classic Pancakes
            [
                'title' => 'Classic Pancakes',
                'slug' => 'classic-pancakes',
                'description' => 'Fluffy homemade pancakes perfect for a delicious breakfast.',
                'cuisine_type' => 'American',
                'meal_type' => 'breakfast',
                'difficulty' => 'beginner',
                'cooking_time' => 20,
                'servings' => 4,
                'calories' => 350,
                'protein' => 8.00,
                'carbs' => 48.00,
                'fats' => 14.00,
                'fiber' => 2.00,
                'sugar' => 12.00,
                'sodium' => 400.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1528207776546-365bb710ee93',
                'health_score' => 72,
                'avg_rating' => 4.60,
                'review_count' => 180,
                'view_count' => 2100,
                'is_featured' => false,
                'allergens' => json_encode(['dairy', 'gluten', 'eggs']),
                'estimated_cost' => 5.00,
            ],

            // 5. Beef Tacos
            [
                'title' => 'Beef Tacos',
                'slug' => 'beef-tacos',
                'description' => 'Spicy Mexican-style beef tacos loaded with fresh vegetables.',
                'cuisine_type' => 'Mexican',
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'cooking_time' => 35,
                'servings' => 4,
                'calories' => 480,
                'protein' => 30.00,
                'carbs' => 42.00,
                'fats' => 21.00,
                'fiber' => 5.00,
                'sugar' => 4.00,
                'sodium' => 680.00,
                'spice_level' => 'spicy',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b',
                'health_score' => 76,
                'avg_rating' => 4.70,
                'review_count' => 145,
                'view_count' => 1800,
                'is_featured' => true,
                'allergens' => json_encode(['dairy']),
                'estimated_cost' => 11.00,
            ],

            // 6. Chicken Sandwich
            [
                'title' => 'Grilled Chicken Sandwich',
                'slug' => 'grilled-chicken-sandwich',
                'description' => 'A healthy grilled chicken sandwich with fresh lettuce and tomatoes.',
                'cuisine_type' => 'American',
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'cooking_time' => 25,
                'servings' => 2,
                'calories' => 420,
                'protein' => 32.00,
                'carbs' => 40.00,
                'fats' => 14.00,
                'fiber' => 5.00,
                'sugar' => 5.00,
                'sodium' => 590.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af',
                'health_score' => 82,
                'avg_rating' => 4.40,
                'review_count' => 90,
                'view_count' => 1100,
                'is_featured' => false,
                'allergens' => json_encode(['gluten', 'dairy']),
                'estimated_cost' => 8.50,
            ],

            // 7. Lentil Curry
            [
                'title' => 'Lentil Curry',
                'slug' => 'lentil-curry',
                'description' => 'A hearty Indian lentil curry packed with plant-based protein and spices.',
                'cuisine_type' => 'Indian',
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'cooking_time' => 45,
                'servings' => 4,
                'calories' => 310,
                'protein' => 18.00,
                'carbs' => 45.00,
                'fats' => 8.00,
                'fiber' => 12.00,
                'sugar' => 6.00,
                'sodium' => 420.00,
                'spice_level' => 'spicy',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe',
                'health_score' => 92,
                'avg_rating' => 4.80,
                'review_count' => 165,
                'view_count' => 1900,
                'is_featured' => true,
                'allergens' => null,
                'estimated_cost' => 7.00,
            ],

            // 8. Fruit Smoothie
            [
                'title' => 'Fresh Fruit Smoothie',
                'slug' => 'fresh-fruit-smoothie',
                'description' => 'A refreshing fruit smoothie made with fresh berries and banana.',
                'cuisine_type' => 'International',
                'meal_type' => 'breakfast',
                'difficulty' => 'beginner',
                'cooking_time' => 5,
                'servings' => 2,
                'calories' => 180,
                'protein' => 5.00,
                'carbs' => 35.00,
                'fats' => 3.00,
                'fiber' => 5.00,
                'sugar' => 22.00,
                'sodium' => 60.00,
                'spice_level' => 'mild',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1553530666-ba11a7da3888',
                'health_score' => 95,
                'avg_rating' => 4.90,
                'review_count' => 250,
                'view_count' => 2800,
                'is_featured' => true,
                'allergens' => null,
                'estimated_cost' => 5.50,
            ],

            // 9. Vegetable Pasta
            [
                'title' => 'Vegetable Pasta',
                'slug' => 'vegetable-pasta',
                'description' => 'A delicious Italian pasta loaded with fresh seasonal vegetables.',
                'cuisine_type' => 'Italian',
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'cooking_time' => 25,
                'servings' => 3,
                'calories' => 390,
                'protein' => 12.00,
                'carbs' => 62.00,
                'fats' => 10.00,
                'fiber' => 8.00,
                'sugar' => 7.00,
                'sodium' => 390.00,
                'spice_level' => 'mild',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601',
                'health_score' => 88,
                'avg_rating' => 4.50,
                'review_count' => 115,
                'view_count' => 1400,
                'is_featured' => false,
                'allergens' => json_encode(['gluten']),
                'estimated_cost' => 8.00,
            ],

            // 10. Chicken Soup
            [
                'title' => 'Healthy Chicken Soup',
                'slug' => 'healthy-chicken-soup',
                'description' => 'A warm and comforting chicken soup with fresh vegetables.',
                'cuisine_type' => 'International',
                'meal_type' => 'lunch',
                'difficulty' => 'beginner',
                'cooking_time' => 40,
                'servings' => 4,
                'calories' => 280,
                'protein' => 26.00,
                'carbs' => 20.00,
                'fats' => 10.00,
                'fiber' => 4.00,
                'sugar' => 5.00,
                'sodium' => 480.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => true,
                'image_url' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd',
                'health_score' => 90,
                'avg_rating' => 4.70,
                'review_count' => 135,
                'view_count' => 1700,
                'is_featured' => false,
                'allergens' => null,
                'estimated_cost' => 9.00,
            ],

            // 11. Chocolate Cake
            [
                'title' => 'Chocolate Cake',
                'slug' => 'chocolate-cake',
                'description' => 'A rich and moist chocolate cake perfect for dessert lovers.',
                'cuisine_type' => 'American',
                'meal_type' => 'dessert',
                'difficulty' => 'medium',
                'cooking_time' => 60,
                'servings' => 8,
                'calories' => 450,
                'protein' => 6.00,
                'carbs' => 62.00,
                'fats' => 20.00,
                'fiber' => 3.00,
                'sugar' => 38.00,
                'sodium' => 300.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
                'health_score' => 55,
                'avg_rating' => 4.80,
                'review_count' => 300,
                'view_count' => 3500,
                'is_featured' => true,
                'allergens' => json_encode(['dairy', 'gluten', 'eggs']),
                'estimated_cost' => 9.50,
            ],

            // 12. French Toast
            [
                'title' => 'French Toast',
                'slug' => 'french-toast',
                'description' => 'Classic French toast served with fresh berries and honey.',
                'cuisine_type' => 'French',
                'meal_type' => 'breakfast',
                'difficulty' => 'easy',
                'cooking_time' => 15,
                'servings' => 2,
                'calories' => 380,
                'protein' => 12.00,
                'carbs' => 48.00,
                'fats' => 15.00,
                'fiber' => 3.00,
                'sugar' => 18.00,
                'sodium' => 350.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => false,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1484723091739-30a097e8f929',
                'health_score' => 70,
                'avg_rating' => 4.60,
                'review_count' => 155,
                'view_count' => 1800,
                'is_featured' => false,
                'allergens' => json_encode(['dairy', 'gluten', 'eggs']),
                'estimated_cost' => 6.00,
            ],

            // 13. Hummus
            [
                'title' => 'Classic Hummus',
                'slug' => 'classic-hummus',
                'description' => 'Creamy Middle Eastern hummus made with chickpeas, tahini and lemon.',
                'cuisine_type' => 'Middle Eastern',
                'meal_type' => 'snack',
                'difficulty' => 'beginner',
                'cooking_time' => 10,
                'servings' => 4,
                'calories' => 240,
                'protein' => 8.00,
                'carbs' => 22.00,
                'fats' => 14.00,
                'fiber' => 6.00,
                'sugar' => 2.00,
                'sodium' => 280.00,
                'spice_level' => 'mild',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1577805947697-89e18249d767',
                'health_score' => 88,
                'avg_rating' => 4.70,
                'review_count' => 180,
                'view_count' => 2000,
                'is_featured' => false,
                'allergens' => json_encode(['sesame']),
                'estimated_cost' => 6.00,
            ],

            // 14. Grilled Chicken
            [
                'title' => 'Grilled Chicken Breast',
                'slug' => 'grilled-chicken-breast',
                'description' => 'Juicy grilled chicken breast seasoned with herbs and spices.',
                'cuisine_type' => 'American',
                'meal_type' => 'dinner',
                'difficulty' => 'easy',
                'cooking_time' => 25,
                'servings' => 2,
                'calories' => 320,
                'protein' => 48.00,
                'carbs' => 4.00,
                'fats' => 12.00,
                'fiber' => 1.00,
                'sugar' => 1.00,
                'sodium' => 420.00,
                'spice_level' => 'medium',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => true,
                'image_url' => 'https://images.unsplash.com/photo-1532550907401-a500c9a57435',
                'health_score' => 94,
                'avg_rating' => 4.80,
                'review_count' => 220,
                'view_count' => 2600,
                'is_featured' => true,
                'allergens' => null,
                'estimated_cost' => 10.00,
            ],

            // 15. Chickpea Salad
            [
                'title' => 'Mediterranean Chickpea Salad',
                'slug' => 'mediterranean-chickpea-salad',
                'description' => 'A healthy Mediterranean chickpea salad with fresh vegetables and herbs.',
                'cuisine_type' => 'Mediterranean',
                'meal_type' => 'lunch',
                'difficulty' => 'beginner',
                'cooking_time' => 15,
                'servings' => 3,
                'calories' => 290,
                'protein' => 12.00,
                'carbs' => 38.00,
                'fats' => 10.00,
                'fiber' => 9.00,
                'sugar' => 6.00,
                'sodium' => 320.00,
                'spice_level' => 'mild',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999',
                'health_score' => 93,
                'avg_rating' => 4.70,
                'review_count' => 140,
                'view_count' => 1600,
                'is_featured' => false,
                'allergens' => null,
                'estimated_cost' => 7.50,
            ],

            // 16. Beef Steak
            [
                'title' => 'Grilled Beef Steak',
                'slug' => 'grilled-beef-steak',
                'description' => 'A tender grilled beef steak served with fresh vegetables.',
                'cuisine_type' => 'American',
                'meal_type' => 'dinner',
                'difficulty' => 'advanced',
                'cooking_time' => 35,
                'servings' => 2,
                'calories' => 620,
                'protein' => 52.00,
                'carbs' => 8.00,
                'fats' => 40.00,
                'fiber' => 2.00,
                'sugar' => 2.00,
                'sodium' => 520.00,
                'spice_level' => 'medium',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => true,
                'image_url' => 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
                'health_score' => 78,
                'avg_rating' => 4.90,
                'review_count' => 275,
                'view_count' => 3200,
                'is_featured' => true,
                'allergens' => null,
                'estimated_cost' => 18.00,
            ],

            // 17. Vegetable Curry
            [
                'title' => 'Spicy Vegetable Curry',
                'slug' => 'spicy-vegetable-curry',
                'description' => 'A colorful and spicy vegetable curry packed with healthy ingredients.',
                'cuisine_type' => 'Indian',
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'cooking_time' => 40,
                'servings' => 4,
                'calories' => 280,
                'protein' => 9.00,
                'carbs' => 38.00,
                'fats' => 11.00,
                'fiber' => 10.00,
                'sugar' => 8.00,
                'sodium' => 390.00,
                'spice_level' => 'extra_spicy',
                'is_vegan' => true,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
                'health_score' => 91,
                'avg_rating' => 4.60,
                'review_count' => 130,
                'view_count' => 1500,
                'is_featured' => false,
                'allergens' => null,
                'estimated_cost' => 7.00,
            ],

            // 18. Grilled Salmon
            [
                'title' => 'Grilled Salmon',
                'slug' => 'grilled-salmon',
                'description' => 'A healthy grilled salmon fillet rich in protein and omega-3 fatty acids.',
                'cuisine_type' => 'Mediterranean',
                'meal_type' => 'dinner',
                'difficulty' => 'advanced',
                'cooking_time' => 25,
                'servings' => 2,
                'calories' => 430,
                'protein' => 42.00,
                'carbs' => 5.00,
                'fats' => 28.00,
                'fiber' => 2.00,
                'sugar' => 2.00,
                'sodium' => 350.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => false,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => true,
                'image_url' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288',
                'health_score' => 94,
                'avg_rating' => 4.90,
                'review_count' => 240,
                'view_count' => 2900,
                'is_featured' => true,
                'allergens' => json_encode(['fish']),
                'estimated_cost' => 16.00,
            ],

            // 19. Mango Lassi
            [
                'title' => 'Mango Lassi',
                'slug' => 'mango-lassi',
                'description' => 'A refreshing and creamy mango yogurt drink inspired by South Asian cuisine.',
                'cuisine_type' => 'Pakistani',
                'meal_type' => 'snack',
                'difficulty' => 'beginner',
                'cooking_time' => 5,
                'servings' => 2,
                'calories' => 210,
                'protein' => 7.00,
                'carbs' => 35.00,
                'fats' => 5.00,
                'fiber' => 2.00,
                'sugar' => 28.00,
                'sodium' => 90.00,
                'spice_level' => 'mild',
                'is_vegan' => false,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => false,
                'image_url' => 'https://images.unsplash.com/photo-1546173159-315724a31696',
                'health_score' => 78,
                'avg_rating' => 4.80,
                'review_count' => 190,
                'view_count' => 2200,
                'is_featured' => false,
                'allergens' => json_encode(['dairy']),
                'estimated_cost' => 5.00,
            ],

            // 20. Keto Egg Breakfast
            [
                'title' => 'Keto Egg Breakfast',
                'slug' => 'keto-egg-breakfast',
                'description' => 'A protein-rich low-carb breakfast with eggs, avocado and fresh vegetables.',
                'cuisine_type' => 'International',
                'meal_type' => 'breakfast',
                'difficulty' => 'easy',
                'cooking_time' => 15,
                'servings' => 2,
                'calories' => 390,
                'protein' => 22.00,
                'carbs' => 8.00,
                'fats' => 30.00,
                'fiber' => 6.00,
                'sugar' => 2.00,
                'sodium' => 330.00,
                'spice_level' => 'medium',
                'is_vegan' => false,
                'is_vegetarian' => true,
                'is_halal' => true,
                'is_gluten_free' => true,
                'is_keto' => true,
                'image_url' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8',
                'health_score' => 92,
                'avg_rating' => 4.70,
                'review_count' => 160,
                'view_count' => 1900,
                'is_featured' => true,
                'allergens' => json_encode(['eggs', 'dairy']),
                'estimated_cost' => 7.50,
            ],
        ];

        foreach ($recipes as $recipe) {

            $recipeData = array_merge($recipe, [
                'user_id' => null,
                'category_id' => $categoryId,
                'instructions' => json_encode([
                    'Prepare all ingredients.',
                    'Follow the recipe preparation steps.',
                    'Cook the ingredients according to the required cooking time.',
                    'Season according to taste.',
                    'Serve fresh and enjoy.'
                ]),
                'video_url' => null,
                'is_ai_generated' => false,
                'is_seasonal' => false,
                'season_tag' => null,
                'source_api' => null,
                'external_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('recipes')->updateOrInsert(
                ['slug' => $recipe['slug']],
                $recipeData
            );
        }

        $this->command->info('20 recipes are now available in MealIt!');
    }
}